apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: work6-t3-rolebinding
subjects:
  - kind: User
    name: user01
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: work6-t3-role
  apiGroup: rbac.authorization.k8s.io
