apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.ingress.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
    nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.protocol }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Release.Name }}-{{ .Values.secret.name }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ (index .Values.ingress.httpPath 0).path }}
            pathType: {{ (index .Values.ingress.httpPath 0).type }}
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.service.name }}
                port:
                  number: {{ .Values.service.portNum }}
