apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: {{ .Values.secret.type }}
data:
  {{ (index .Values.secret.key 0).name }}: {{ (index .Values.secret.key 0).value }}
  {{ (index .Values.secret.key 1).name }}: {{ (index .Values.secret.key 1).value }}