apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.deployment.labels.app }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.portNum }}
