apiVersion: v1
kind: Pod
metadata:
  name: pod-test-echoserver
  labels:
    env: test
    app: echo
spec:
  containers:
    - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      name: echoserver
