global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: docker-metrics
    static_configs:

      - targets: [security:3000]
        labels:
          app: security

      - targets: [uploader:3000]
        labels:
          app: uploader

      - targets: [storage:9000]
        labels:
          __metrics_path__: /minio/v2/metrics/cluster
          app: storage

