apiVersion: apps/v1
kind: Deployment
metadata:
  name: work4-t2-deployment-backend
  labels:
    env: test
    app: work4-t2-multitool
spec:
  replicas: 2
  selector:
    matchLabels:
      env: test
      app: work4-t2-multitool
  template:
    metadata:
      labels:
        env: test
        app: work4-t2-multitool
    spec:
      containers:
        - image: wbitt/network-multitool
          name: multitool
