apiVersion: v1
kind: Service
metadata:
  name: work4-t2-svc-backend
spec:
  selector:
    env: test
    app: work4-t2-multitool
  ports:
    - name: multitool-http
      port: 80
    - name: multitool-https
      port: 443
