apiVersion: v1
kind: ConfigMap
metadata:
  name: work11-t3-configmap
data:
  index-v1.html: |
    <html>
    <head>
        <title>App V1</title>
    </head>
    </html>
  index-v2.html: |
    <html>
    <head>
        <title>App V2</title>
    </head>
    </html>
