apiVersion: v1
kind: Service
metadata:
  name: work10-svc-frontend
  namespace: app
spec:
  selector:
    app: frontend
  ports:
    - name: multitool-http
      port: 80
    - name: multitool-https
      port: 443
