apiVersion: v1
kind: Service
metadata:
  name: work4-t1-svc
spec:
  selector:
    env: test
    app: work4-t1-app
  ports:
    - name: nginx-http
      port: 9001
      targetPort: 80
    - name: multitool-http
      port: 9002
      targetPort: 8080
    - name: multitool-https
      port: 9003
      targetPort: 8443
