apiVersion: v1
kind: Service
metadata:
  name: work4-t1-svc-nodeport
spec:
  selector:
    env: test
    app: work4-t1-app
  ports:
    - name: nginx-http
      port: 80
    - name: multitool-http
      port: 8080
    - name: multitool-https
      port: 8443
  type: NodePort
