volumes:
  data_minio:
  data_grafana:
  data_prometheus:

services:
  storage:
    image: minio/minio:latest
    command: server /data
    restart: always
    expose: 
      - 9000
    environment:
      MINIO_ROOT_USER: ${Storage_AccessKey:-STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${Storage_Secret:-STORAGE_SECRET_KEY}
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - data_minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    depends_on:
      - storage 
    image: minio/mc
    restart: on-failure
    entrypoint: > 
      /bin/sh -c "      
      /usr/bin/mc alias set micsv-w2-t3-storage http://storage:9000 ${Storage_AccessKey-STORAGE_ACCESS_KEY} ${Storage_Secret-STORAGE_SECRET_KEY} &&
      /usr/bin/mc mb --ignore-existing micsv-w2-t3-storage/${Storage_Bucket:-data} &&
      /usr/bin/mc anonymous set download micsv-w2-t3-storage/${Storage_Bucket:-data} &&
      exit 0;
      "

  uploader:
    depends_on:
      - storage
      - createbuckets
    build: ./configs/uploader
    expose: 
      - 3000
    environment:
      PORT: 3000
      S3_HOST: storage
      S3_PORT: 9000
      S3_ACCESS_KEY: ${Storage_AccessKey:-STORAGE_ACCESS_KEY}
      S3_ACCESS_SECRET: ${Storage_Secret:-STORAGE_SECRET_KEY}
      S3_BUCKET: ${Storage_Bucket:-STORAGE_BUCKET}
  
  security:
    build: ./configs/security
    expose: 
      - 3000
    environment:
      PORT: 3000

  gateway:
    depends_on:
      - storage
      - uploader
      - security
    image: nginx:alpine
    volumes:
      - ./configs/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8080"      

  grafana:
    image: grafana/grafana:main-ubuntu
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./configs/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./configs/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./configs/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
      - data_grafana:/var/lib/grafana/
    ports:
      - 8081:3000
  
  prometheus:
    image: prom/prometheus:main
    restart: on-failure
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - data_prometheus:/var/lib/prometheus/
    expose:
      - 9090
