---

services:
  setup:
    image: elastic/elasticsearch:${STACK_VERSION}
    volumes:
      - ./configs/elasticsearch/instances.yml:/usr/share/elasticsearch/config/instances.yml
      - ./data/certs:/usr/share/elasticsearch/config/certs
    user: "0"
    command: >
      bash -c '
        if [ ! -f config/certs/ca.zip ]; then
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        until curl -s --cacert config/certs/ca/ca.crt https://elasticsearch-01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://elasticsearch-01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/elasticsearch-01/elasticsearch-01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  elasticsearch-01:
    depends_on:
      setup:
        condition: service_healthy
    image: elastic/elasticsearch:${STACK_VERSION}
    volumes:
      - ./data/certs:/usr/share/elasticsearch/config/certs
      - ./data/elasticsearch/elasticsearch-01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=elasticsearch-01
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=elasticsearch-01,elasticsearch-02
      - discovery.seed_hosts=elasticsearch-02
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/elasticsearch-01/elasticsearch-01.key
      - xpack.security.http.ssl.certificate=certs/elasticsearch-01/elasticsearch-01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/elasticsearch-01/elasticsearch-01.key
      - xpack.security.transport.ssl.certificate=certs/elasticsearch-01/elasticsearch-01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
      - xpack.ml.use_auto_machine_memory_percent=true
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  elasticsearch-02:
    depends_on:
      - elasticsearch-01
    image: elastic/elasticsearch:${STACK_VERSION}
    volumes:
      - ./data/certs:/usr/share/elasticsearch/config/certs
      - ./data/elasticsearch/elasticsearch-02:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch-02
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=elasticsearch-01,elasticsearch-02
      - discovery.seed_hosts=elasticsearch-01
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/elasticsearch-02/elasticsearch-02.key
      - xpack.security.http.ssl.certificate=certs/elasticsearch-02/elasticsearch-02.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/elasticsearch-02/elasticsearch-02.key
      - xpack.security.transport.ssl.certificate=certs/elasticsearch-02/elasticsearch-02.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
      - xpack.ml.use_auto_machine_memory_percent=true
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      elasticsearch-01:
        condition: service_healthy
      elasticsearch-02:
        condition: service_healthy
    image: elastic/kibana:${STACK_VERSION}
    volumes:
      - ./data/certs:/usr/share/kibana/config/certs
      - ./data/kibana:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://elasticsearch-01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  logstash:
    depends_on:
      elasticsearch-01:
        condition: service_healthy
    image: elastic/logstash:${STACK_VERSION}
    restart: on-failure
    volumes:
      - ./configs/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./configs/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./data/certs:/usr/share/logstash/certs
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

  filebeat:
    depends_on:
      - logstash
    image: elastic/filebeat:${STACK_VERSION}
    user: root
    restart: on-failure
    volumes:
      - ./configs/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./configs/filebeat/system.yml:/usr/share/filebeat/modules.d/system.yml
      - /var/log/syslog:/var/log/syslog
      - /var/log/auth.log:/var/log/auth.log
      - ./data/certs:/usr/share/filebeat/certs/
    command: >
      bash -c '
        rm /usr/share/filebeat/modules.d/system.yml.disabled
        filebeat modules enable system -e --strict.perms=false;
        filebeat setup --pipelines -e --strict.perms=false \
          -E output.logstash.enabled=false \
          -E output.elasticsearch.hosts=["https://elasticsearch-01:9200"] \
          -E output.elasticsearch.username=elastic \
          -E output.elasticsearch.password=$ELASTIC_PASSWORD \
          -E output.elasticsearch.ssl.certificate_authorities=["/usr/share/filebeat/certs/ca/ca.crt"];
        filebeat -e --strict.perms=false;
      '
