apiVersion: v1
kind: Service
metadata:
  name: work6-t1-svc
spec:
  selector:
    env: test
    app: work6-t1-app
  ports:
    - name: nginx-http
      port: 80
    - name: multitool-http
      port: 8080
    - name: multitool-https
      port: 8443
